SKILL(DISARM_PHYS,		100,	5,		STAT_DEX,		"physical disarming")
SKILL(DISARM_MAGIC,		100,	5,		STAT_INT,		"magical disarming")
SKILL(DEVICE,			150,	10,		STAT_INT,		"magic devices")
SKILL(SAVE,				200,	15,		STAT_WIS,		"saving throws")
SKILL(SEARCH,			100,	5,		STAT_INT,		"perception")
SKILL(STEALTH,			200,	10,		STAT_DEX,		"stealth")
SKILL(TO_HIT_MELEE,		250,	20,		STAT_DEX,		"melee")
SKILL(TO_HIT_BOW,		250,	15,		STAT_DEX,		"shooting")
SKILL(TO_HIT_THROW,		200,	10,		STAT_STR,		"throwing")
SKILL(DIGGING,			150,	5,		STAT_STR,		"digging")
SKILL(MAGIC,			300,	20,		STAT_NONE,		"magic")
SKILL(HEALTH,			300,	10,		STAT_CON,		"resilience")
