//    tag                       rarity  stat1   
SKILL(DISARM_PHYS,		100,	5,		STAT_DEX,	STAT_INT,	"physical disarming")
SKILL(DISARM_MAGIC,		100,	5,		STAT_INT,	STAT_DEX,	"magical disarming")
SKILL(DEVICE,			150,	10,		STAT_INT,	STAT_WIS,	"magic devices")
SKILL(SAVE,				200,	15,		STAT_WIS,	STAT_DEX,	"saving throws")
SKILL(SEARCH,			100,	5,		STAT_INT,	STAT_WIS,	"perception")
SKILL(STEALTH,			200,	10,		STAT_DEX,	STAT_INT,	"stealth")
SKILL(TO_HIT_MELEE,		250,	20,		STAT_DEX,	STAT_STR,	"melee")
SKILL(TO_HIT_BOW,		250,	15,		STAT_DEX,	STAT_STR,	"shooting")
SKILL(TO_HIT_THROW,		200,	10,		STAT_STR,	STAT_DEX,	"throwing")
SKILL(DIGGING,			150,	5,		STAT_STR,	STAT_WIS,	"digging")
SKILL(MAGIC,			300,	20,		STAT_NONE,	STAT_NONE,	"magic")
SKILL(HEALTH,			300,	10,		STAT_CON,	STAT_STR,	"resilience")
