/**
 * \file list-mon-race-flags.h
 * \brief monster race flags
 *
 */
/* symbol			type					descr	*/
RF(NONE,			RFT_NONE,		0,		"")
RF(UNIQUE,			RFT_OBV,		5,		"")
RF(QUESTOR,			RFT_OBV,		5,		"")
RF(MALE,			RFT_OBV,		0,		"")
RF(FEMALE,			RFT_OBV,		0,		"")
RF(GROUP_AI,		RFT_OBV,		0,		"")
RF(NAME_COMMA,		RFT_OBV,		0,		"")
RF(CHAR_CLEAR,		RFT_DISP,		0,		"")
RF(ATTR_RAND,		RFT_DISP,		0,		"")
RF(ATTR_CLEAR,		RFT_DISP,		0,		"")
RF(ATTR_MULTI,		RFT_DISP,		0,		"")
RF(ATTR_FLICKER,	RFT_DISP,		0,		"")
RF(FORCE_DEPTH,		RFT_GEN,		5,		"")
RF(FORCE_SLEEP,		RFT_GEN,		5,		"")
RF(FORCE_EXTRA,		RFT_GEN,		0,		"")
RF(SEASONAL,		RFT_GEN,		-5,		"")
RF(UNAWARE,			RFT_NOTE,		5,		"")
RF(MULTIPLY,		RFT_NOTE,		-5,		"")
RF(REGENERATE,		RFT_NOTE,		-2,		"")
RF(FRIGHTENED,		RFT_BEHAV,		2,		"")
RF(NEVER_BLOW,		RFT_BEHAV,		0,		"")
RF(NEVER_MOVE,		RFT_BEHAV,		5,		"")
RF(RAND_25,			RFT_BEHAV,		2,		"")
RF(RAND_50,			RFT_BEHAV,		5,		"")
RF(MIMIC_INV,		RFT_BEHAV,		-2,		"")
RF(STUPID,			RFT_BEHAV,		0,		"")
RF(SMART,			RFT_BEHAV,		0,		"")
RF(SPIRIT,			RFT_BEHAV,		0,		"")
RF(POWERFUL,		RFT_BEHAV,		2,		"")
RF(ONLY_GOLD,		RFT_DROP,		0,		"")
RF(ONLY_ITEM,		RFT_DROP,		0,		"")
RF(DROP_40,			RFT_DROP,		0,		"")
RF(DROP_60,			RFT_DROP,		1,		"")
RF(DROP_1,			RFT_DROP,		2,		"")
RF(DROP_2,			RFT_DROP,		3,		"")
RF(DROP_3,			RFT_DROP,		4,		"")
RF(DROP_4,			RFT_DROP,		5,		"")
RF(DROP_GOOD,		RFT_DROP,		2,		"")
RF(DROP_GREAT,		RFT_DROP,		5,		"")
RF(DROP_20,			RFT_DROP,		0,		"")
RF(INVISIBLE,		RFT_DET,		-2,		"invisible")
RF(COLD_BLOOD,		RFT_DET,		0,		"cold blooded")
RF(EMPTY_MIND,		RFT_DET,		0,		"not detected by telepathy")
RF(WEIRD_MIND,		RFT_DET,		0,		"rarely detected by telepathy")
RF(OPEN_DOOR,		RFT_ALTER,		0,		"open doors")
RF(BASH_DOOR,		RFT_ALTER,		0,		"bash down doors")
RF(PASS_WALL,		RFT_ALTER,		-5,		"pass through walls")
RF(KILL_WALL,		RFT_ALTER,		-2,		"bore through walls")
RF(SMASH_WALL,		RFT_ALTER,		-2,		"smash walls")
RF(MOVE_BODY,		RFT_ALTER,		0,		"push past weaker monsters")
RF(KILL_BODY,		RFT_ALTER,		0,		"destroy weaker monsters")
RF(TAKE_ITEM,		RFT_ALTER,		0,		"pick up objects")
RF(KILL_ITEM,		RFT_ALTER,		0,		"destroy objects")
RF(CLEAR_WEB,		RFT_ALTER,		0,		"clear webs")
RF(PASS_WEB,		RFT_ALTER,		0,		"pass through webs")
RF(ORC,				RFT_RACE_N,		0,		"orc")
RF(TROLL,			RFT_RACE_N,		0,		"troll")
RF(GIANT,			RFT_RACE_N,		0,		"giant")
RF(DRAGON,			RFT_RACE_N,		2,		"dragon")
RF(DEMON,			RFT_RACE_N,		2,		"demon")
RF(ANIMAL,			RFT_RACE_A,		0,		"natural")
RF(EVIL,			RFT_RACE_A,		0,		"evil")
RF(UNDEAD,			RFT_RACE_A,		0,		"undead")
RF(NONLIVING,		RFT_RACE_A,		0,		"nonliving")
RF(METAL,			RFT_RACE_A,		0,		"metal")
RF(HURT_LIGHT,		RFT_VULN,		2,		"bright light")
RF(HURT_ROCK,		RFT_VULN,		0,		"rock remover")
RF(HURT_FIRE,		RFT_VULN_I,		2,		"fire")
RF(HURT_COLD,		RFT_VULN_I,		2,		"cold")
RF(IM_ACID,			RFT_RES,		-2,		"acid")
RF(IM_ELEC,			RFT_RES,		-2,		"lightning")
RF(IM_FIRE,			RFT_RES,		-2,		"fire")
RF(IM_COLD,			RFT_RES,		-2,		"cold")
RF(IM_POIS,			RFT_RES,		-2,		"poison")
RF(IM_NETHER,		RFT_RES,		-2,		"nether")
RF(IM_WATER,		RFT_RES,		-2,		"water")
RF(IM_PLASMA,		RFT_RES,		-2,		"plasma")
RF(IM_NEXUS,		RFT_RES,		-2,		"nexus")
RF(IM_DISEN,		RFT_RES,		-2,		"disenchantment")
RF(RES_PIERCING,	RFT_RES,		-5,		"piercing")
RF(RES_SLASHING,	RFT_RES,		-5,		"slashing")
RF(RES_BLUDGEONING,	RFT_RES,		-5,		"bludgeoning")
RF(NO_FEAR,			RFT_PROT,		-2,		"frightened")
RF(NO_STUN,			RFT_PROT,		-2,		"stunned")
RF(NO_CONF,			RFT_PROT,		-2,		"confused")
RF(NO_SLEEP,		RFT_PROT,		-2,		"slept")
RF(NO_HOLD,			RFT_PROT,		-2,		"held")
RF(NO_SLOW,			RFT_PROT,		-2,		"slowed")
/* end flags */
